function mu = build_mu(mesh, epsilon, ...
                       laminar_viscosity, ...
                       smagorinsky_coefficient, ...
                       smagorinsky_caracteristic_length)

  mu = zeros(size(mesh.elements, 1), 1);
  for el = 1:size(mesh.elements, 1)
    epsilon_norm = sqrt(sum((epsilon(:, :, el).^2)(:)));
      
    mu(el) = laminar_viscosity + 2 ...
				 * smagorinsky_coefficient ...
				 * smagorinsky_caracteristic_length^2 ...
				 * epsilon_norm;
  end
